2025-09-05 15:31:56,683 - large_scale_cognitive_test_client_2 - INFO - Starting client 2 with config: {'client_id': 2, 'server_address': '0.0.0.0:8080', 'experiment_name': 'large_scale_cognitive_test', 'seed': 458, 'batch_size': 32, 'epochs': 2, 'learning_rate': 0.001, 'attack_enabled': True, 'attack_type': 'label_flip', 'attack_intensity': 0.2}
2025-09-05 15:32:01,320 - large_scale_cognitive_test_client_2 - INFO - Client 2 initialized with 6003 training samples
2025-09-05 15:32:01,320 - large_scale_cognitive_test_client_2 - INFO - Client 2 connecting to 0.0.0.0:8080
2025-09-05 15:32:01,321 - flwr - WARNING - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.
	Instead, use the `flower-supernode` CLI command to start a SuperNode as shown below:

		$ flower-supernode --insecure --superlink='<IP>:<PORT>'

	To view all available options, run:

		$ flower-supernode --help

	Using `start_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.
        
2025-09-05 15:32:01,333 - flwr - DEBUG - Opened insecure gRPC connection (no certificates were passed)
2025-09-05 15:32:01,334 - flwr - DEBUG - ChannelConnectivity.IDLE
2025-09-05 15:32:01,335 - flwr - DEBUG - ChannelConnectivity.TRANSIENT_FAILURE
2025-09-05 15:32:01,537 - flwr - DEBUG - gRPC channel closed
2025-09-05 15:32:01,537 - large_scale_cognitive_test_client_2 - ERROR - Client 2 failed: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:0.0.0.0:8080: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:0.0.0.0:8080: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-09-05 15:38:13,650 - large_scale_cognitive_test_client_2 - INFO - Starting client 2 with config: {'client_id': 2, 'server_address': '0.0.0.0:8080', 'experiment_name': 'large_scale_cognitive_test', 'seed': 458, 'batch_size': 32, 'epochs': 2, 'learning_rate': 0.001, 'attack_enabled': True, 'attack_type': 'label_flip', 'attack_intensity': 0.2}
2025-09-05 15:38:18,361 - large_scale_cognitive_test_client_2 - INFO - Client 2 initialized with 6003 training samples
2025-09-05 15:38:18,362 - large_scale_cognitive_test_client_2 - INFO - Client 2 connecting to 0.0.0.0:8080
2025-09-05 15:38:18,362 - flwr - WARNING - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.
	Instead, use the `flower-supernode` CLI command to start a SuperNode as shown below:

		$ flower-supernode --insecure --superlink='<IP>:<PORT>'

	To view all available options, run:

		$ flower-supernode --help

	Using `start_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.
        
2025-09-05 15:38:18,375 - flwr - DEBUG - Opened insecure gRPC connection (no certificates were passed)
2025-09-05 15:38:18,376 - flwr - DEBUG - ChannelConnectivity.IDLE
2025-09-05 15:38:18,377 - flwr - DEBUG - ChannelConnectivity.TRANSIENT_FAILURE
2025-09-05 15:38:18,581 - flwr - DEBUG - gRPC channel closed
2025-09-05 15:38:18,581 - large_scale_cognitive_test_client_2 - ERROR - Client 2 failed: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:0.0.0.0:8080: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:0.0.0.0:8080: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14}"
>
2025-09-05 15:40:59,403 - large_scale_cognitive_test_client_2 - INFO - Starting client 2 with config: {'client_id': 2, 'server_address': '20.169.237.127:8080', 'experiment_name': 'large_scale_cognitive_test', 'seed': 458, 'batch_size': 32, 'epochs': 2, 'learning_rate': 0.001, 'attack_enabled': True, 'attack_type': 'label_flip', 'attack_intensity': 0.2}
2025-09-05 15:41:04,152 - large_scale_cognitive_test_client_2 - INFO - Client 2 initialized with 6003 training samples
2025-09-05 15:41:04,153 - large_scale_cognitive_test_client_2 - INFO - Client 2 connecting to 20.169.237.127:8080
2025-09-05 15:41:04,153 - flwr - WARNING - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.
	Instead, use the `flower-supernode` CLI command to start a SuperNode as shown below:

		$ flower-supernode --insecure --superlink='<IP>:<PORT>'

	To view all available options, run:

		$ flower-supernode --help

	Using `start_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.
        
2025-09-05 15:41:04,166 - flwr - DEBUG - Opened insecure gRPC connection (no certificates were passed)
2025-09-05 15:41:04,167 - flwr - DEBUG - ChannelConnectivity.IDLE
2025-09-05 15:41:04,168 - flwr - DEBUG - ChannelConnectivity.CONNECTING
2025-09-05 15:41:04,403 - flwr - DEBUG - ChannelConnectivity.TRANSIENT_FAILURE
2025-09-05 15:41:04,610 - flwr - DEBUG - gRPC channel closed
2025-09-05 15:41:04,610 - large_scale_cognitive_test_client_2 - ERROR - Client 2 failed: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)"}"
>
