2025-09-05 15:31:59,418 - large_scale_cognitive_test_client_3 - INFO - Starting client 3 with config: {'client_id': 3, 'server_address': '0.0.0.0:8080', 'experiment_name': 'large_scale_cognitive_test', 'seed': 459, 'batch_size': 32, 'epochs': 2, 'learning_rate': 0.001, 'attack_enabled': True, 'attack_type': 'label_flip', 'attack_intensity': 0.2}
2025-09-05 15:32:03,375 - large_scale_cognitive_test_client_3 - INFO - Client 3 initialized with 5881 training samples
2025-09-05 15:32:03,375 - large_scale_cognitive_test_client_3 - INFO - Client 3 connecting to 0.0.0.0:8080
2025-09-05 15:32:03,375 - flwr - WARNING - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.
	Instead, use the `flower-supernode` CLI command to start a SuperNode as shown below:

		$ flower-supernode --insecure --superlink='<IP>:<PORT>'

	To view all available options, run:

		$ flower-supernode --help

	Using `start_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.
        
2025-09-05 15:32:03,390 - flwr - DEBUG - Opened insecure gRPC connection (no certificates were passed)
2025-09-05 15:32:03,390 - flwr - DEBUG - ChannelConnectivity.IDLE
2025-09-05 15:32:03,391 - flwr - DEBUG - ChannelConnectivity.CONNECTING
2025-09-05 15:32:03,392 - flwr - DEBUG - gRPC channel closed
2025-09-05 15:32:03,392 - large_scale_cognitive_test_client_3 - ERROR - Client 3 failed: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:0.0.0.0:8080: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:0.0.0.0:8080: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14}"
>
2025-09-05 15:38:16,405 - large_scale_cognitive_test_client_3 - INFO - Starting client 3 with config: {'client_id': 3, 'server_address': '0.0.0.0:8080', 'experiment_name': 'large_scale_cognitive_test', 'seed': 459, 'batch_size': 32, 'epochs': 2, 'learning_rate': 0.001, 'attack_enabled': True, 'attack_type': 'label_flip', 'attack_intensity': 0.2}
2025-09-05 15:38:20,251 - large_scale_cognitive_test_client_3 - INFO - Client 3 initialized with 5881 training samples
2025-09-05 15:38:20,251 - large_scale_cognitive_test_client_3 - INFO - Client 3 connecting to 0.0.0.0:8080
2025-09-05 15:38:20,252 - flwr - WARNING - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.
	Instead, use the `flower-supernode` CLI command to start a SuperNode as shown below:

		$ flower-supernode --insecure --superlink='<IP>:<PORT>'

	To view all available options, run:

		$ flower-supernode --help

	Using `start_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.
        
2025-09-05 15:38:20,267 - flwr - DEBUG - Opened insecure gRPC connection (no certificates were passed)
2025-09-05 15:38:20,268 - flwr - DEBUG - ChannelConnectivity.IDLE
2025-09-05 15:38:20,268 - flwr - DEBUG - ChannelConnectivity.TRANSIENT_FAILURE
2025-09-05 15:38:20,477 - flwr - DEBUG - gRPC channel closed
2025-09-05 15:38:20,477 - large_scale_cognitive_test_client_3 - ERROR - Client 3 failed: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:0.0.0.0:8080: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:0.0.0.0:8080: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14}"
>
2025-09-05 15:41:02,487 - large_scale_cognitive_test_client_3 - INFO - Starting client 3 with config: {'client_id': 3, 'server_address': '20.169.237.127:8080', 'experiment_name': 'large_scale_cognitive_test', 'seed': 459, 'batch_size': 32, 'epochs': 2, 'learning_rate': 0.001, 'attack_enabled': True, 'attack_type': 'label_flip', 'attack_intensity': 0.2}
2025-09-05 15:41:06,309 - large_scale_cognitive_test_client_3 - INFO - Client 3 initialized with 5881 training samples
2025-09-05 15:41:06,309 - large_scale_cognitive_test_client_3 - INFO - Client 3 connecting to 20.169.237.127:8080
2025-09-05 15:41:06,309 - flwr - WARNING - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.
	Instead, use the `flower-supernode` CLI command to start a SuperNode as shown below:

		$ flower-supernode --insecure --superlink='<IP>:<PORT>'

	To view all available options, run:

		$ flower-supernode --help

	Using `start_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.
        
2025-09-05 15:41:06,324 - flwr - DEBUG - Opened insecure gRPC connection (no certificates were passed)
2025-09-05 15:41:06,325 - flwr - DEBUG - ChannelConnectivity.IDLE
2025-09-05 15:41:06,326 - flwr - DEBUG - ChannelConnectivity.CONNECTING
2025-09-05 15:41:06,568 - flwr - DEBUG - ChannelConnectivity.TRANSIENT_FAILURE
2025-09-05 15:41:06,776 - flwr - DEBUG - gRPC channel closed
2025-09-05 15:41:06,777 - large_scale_cognitive_test_client_3 - ERROR - Client 3 failed: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)"}"
>
